# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18MvvdIGWI2yNgwUxfDu7jcC-7DnVKJrW
"""

# 양의 정수 x가 하샤드 수이려면 x의 자릿수의 합으로 x가 나눠져야 한다.
# ex) 18 -> 1+8=9, 18%9 = 0

x=11

# 1차 풀이.
# 양의 정수 x를 문자열로 전환하여 리스트로 각 자릿수를 추출한 후
# 다시 int형으로 전환하여 더해 자릿수의 합을 도출
# x를 도출 결과로 나누어 하샤드 수 검출.
x_str_sum=0
for i in str(x):
    x_str_sum += int(i)
if(x%x_str_sum == 0):
    answer = True
else:
    answer = False

answer

# 삼항 방정식을 사용해서

x_str_sum=0
for i in str(x):
    x_str_sum += int(i)
answer = True if (x%x_str_sum == 0) else False
answer

# 리스트 컴프리헨션을 사용해서
answer = x % sum([int(i) for i in str(x)]) == 0
answer





























