# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15rcMUdR1NkPm0t5BjQS-T309gf1kiT_L
"""

# 첫째 줄에는 현재 시각
# 둘째 줄에는 요리하는데 필요한 시각
# 결과

a, b = map(int, input().split())
c = int(input())

# c는 분단위로 시간, 분으로 나눠줘야한다.
c_hour = (c//60) # c(조리시간) 시간
c_min = c%60# c(조리시간) 분
print(f"{c_hour} {c_min}")

# c를 a와 b에 더해준다.
if b+c_min >= 60: # 조리시간(분) + 현재시간(분) 60분을 넘으면
    min = b+c_min - 60 # 시간은 올려주고 분만 표기
    if a+c_hour+1 >= 24: # 올림 시간을 포함해서 24를 넘는다면
        hour = a+c_hour-24+1 # 다음날 시간으로 넘어간다.
    else:
        hour = a+c_hour+1# 올림 시간이 24시를 넘지 않는다면 조리시간(시간) + 현재시간(시간) + 올림시간
else: 
    min = b+c_min
    if a+c_hour >= 24:
        hour = a+c_hour-24
    else:
        hour = a+c_hour
print(f"{hour} {min}")

# 압축 버전.
a, b = map(int, input().split())
c = int(input())
if b+(c%60) >= 60:
    min = b+(c%60) - 60
    if a+(c//60)+1 >= 24:
        hour = a+(c//60)-24+1
    else:
        hour = a+(c//60)+1
else:
    min = b+(c%60)
    if a+(c//60) >= 24:
        hour = a+(c//60)-24
    else:
        hour = a+(c//60)

print(f"{hour} {min}")







