# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18MvvdIGWI2yNgwUxfDu7jcC-7DnVKJrW
"""

# A = 고정비용
# B = 가변비용(한대당)
# C = 노트북 가격
# result = 손익분기점

A = 1000
B = 70
C = 170
if B >= C :
    break_even_point = -1
else:
    break_even_point = int(A/(C-B))+1
print(break_even_point)

a = 10.7 # 정수로 강제 형변환 시킬때는 내림인것을 확인.
b = int(a)
b

# 정리해서 삼항연산자로 풀면.
a, b, c = map(int, input().split())
print(-1 if b >= c else int(a/(c-b))+1)

























